# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-26 00:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0003_auto_20170926_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='dj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='songlist',
            name='dj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song_lists', to=settings.AUTH_USER_MODEL),
        ),
    ]
