@startuml
:DJ: as DJ
:Requester: as R
(DJ Logs In) as Login
(DJ Creates an Event) as Create
(DJ Activates an Event) as Activate
(DJ Receives Song Request) as Receive
(Requester Connects to an Active Event) as Connects
(Requester Submits a Song Request to the DJ) as Submits
(Requester's Song is Validated) as Validated

DJ -> Login
Login ..> Create: <<includes>>
Create ..> Activate: <<extends>>
Activate ..> Receive: <<includes>>

R -> Connects
Connects ..> Submits: <<extends>>
Submits ..> Validated: <<includes>>
Validated ..> Receive: <<includes>>

@enduml