# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-27 02:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_djprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djprofile',
            name='display_name',
            field=models.CharField(default='DJ Cool Cat', max_length=255),
            preserve_default=False,
        ),
    ]
